### ISSUE TITLE
extract the block content into a method

### ISSUE THREAD

**Issue by madziaf** [CodePadawans/ataru#27]
in order not to iterate over ARGV array twice
and be able to call this method from Rake task

**Comment by moonglum** [comment]
Is this about this piece of code?

``` ruby
file_names.each do |file_name|
# STARTING HERE
if file_name.nil?
puts "ataru: please give the file name"
puts "usage: ataru.rb <filename>"
exit 1
elsif !(file_name =~ /.+\.md/)
puts "ataru: #{file_name} is not a markdown file"
puts "ataru: markdown file required"
exit 2
elsif File.file?(file_name) == false
puts "ataru: #{file_name} file not found"
exit 3
end
# STOP HERE
end
```

**Comment by nanoparsec** [comment]
Yes, this is a part of the code :)

**Comment by schultyy** [comment]
1. Create a new class `Application` in `lib/ataru`
2. Create a new method `run_tests_for_file` which accepts one parameter: `filename`
3. Move the code which reads the file, does traversing and executing the code examples into this method.
4. In `bin/ataru`, require the `Application` class, instantiate it and call `run_tests_for_file`

**Comment by moonglum** [comment]
`file_names` is ARGV. ARGV are the arguments provided to your application. I would suggest to implement code that makes the following work:

``` ruby
arguments = ArgumentChecker.new(file_names)
arguments.each do |argument|
  # Do something with arguments
end
```

The `each` method on arguments does the checking above, so the code in the `do` block doesn't need to care about it at all. What do you think about that, Padawans? :smile: 

You could also call it CheckedArguments. Would also be quite descriptive IMHO.

**Comment by schultyy** [comment]
@moonglum fine with this :)

**Comment by schultyy** [comment]
@moonglum Does `ArgumentChecker` automatically exit if it finds a filename whose validation failed?

**Comment by moonglum** [comment]
@schultyy Would be ok for me for the beginning. From a separation of concerns part it is not great, but I think for the sake of simplicity it is ok for the beginning!

**Comment by schultyy** [comment]
@moonglum kk

**Comment by code-later** [comment]
I like the proposal from @moonglum. And for now I would say just move the `exit` calls to the `ArgumentChecker`. This is not the cleanest possible solution, but it is good enough for now ;-)

**Comment by madziaf** [comment]
@moonglum ArgumentChecker has no method then?

**Comment by schultyy** [comment]
@madziaf @moonglum I suggest that `ArgumentChecker` has a method for validation, so object initialization and the actual check is divided.

**Comment by code-later** [comment]
@schultyy I agree. The validation should be separated from the initialization of the object.

@madziaf Regarding your question: If you incorporate the suggestion @schultyy made you would end up  with two methods, one for the validation (i.e. `valid_arguments?`) and `each` to iterate over the file names.

Regarding the `each` method: I assume you asked if there were any methods because `arguments.each` looks like iterating over an array. But `arguments` is not meant to be an array in this case. It just has one of the many methods an array has too (this concept is also known as **Duck Typing**: If it quacks like a duck or talks like a duck, it maybe is a duck). The next question would be how to implement something like `each`? First of all we should look at the _method signature_, that is how it gets called:

``` ruby
arguments.each do |arg|
  # do something with arg
end
```

You pass a block to each which again expects that one parameter is passed to the block (as a reminder: The block that is between `do` and `end`. The parameter for the block is defined between the `|` symbols. This is very much like a "normal" method). Ok, now we now how the method should look like. Next up is how to use this block inside a method. Basically you can pass a block to any method, no matter if the method needs arguments or not:

``` ruby
def call_me
  puts "maybe"
end

call_me do
  puts "This is crazy"
end
```

Can you tell what will be the output of that method? Think a moment about it…

The answer is `"maybe"`! That's what you said, right? But why is `"This is crazy"` not printed? The answer is simply no one executed or _called_ the block! So how do we call it, you ask? You use the `yield` keyword:

``` ruby
def call_me
  puts "maybe"
  yield
end

call_me do
  puts "This is crazy"
end
```

Now `"This is crazy"` will be printed after `"maybe"`. By the way, you can call the block as many times you want. Just like with any other method. The last thing that is missing now is passing an argument to the block. Again this is done as with any other method you want to pass arguments to:

``` ruby
def call_me
  puts "maybe"
  yield("This is crazy")
end

call_me do |message|
  puts message
end
```

Again, the output will be the same as before, but this time we passed the message to print inside the block as an argument.

As I already said, I think the solution you implemented in #31 is pretty neat. But still, if you're up for a little challenge, maybe you want to try to incorporate the block feature. If you have any questions, just call me ;-)

**Comment by schultyy** [comment]
@railsbros-dirk Wow, well explained :)

**Comment by code-later** [comment]
@schultyy :bow:
