### ISSUE TITLE
Validate Codesample

### ISSUE THREAD

**Issue by nanoparsec** [CodePadawans/ataru#30]
In my documentations I will often write examples like that:

a = 1 + 2
a #=> 3
Maybe you could take that and transform it into a test case like that:

def test_something
  a = 1 + 2
  assert_equal 3, a
end
In my experience the "fat arrow" (=>) is a common symbol to say: This is the result of this line. And as a reader I would expect that this is really the result of that line :wink: So ataru could check if that is really the case.

**Comment by moonglum** [comment]
Yay :smile_cat:

**Comment by schultyy** [comment]
@madziaf and me discussed about the hash rocket. The following will be possible concerning validation:

``` ruby
a = 2 + 3
a #=> 5
```

But this not:

``` ruby
2 + 5
#=> 5
```

This should also be mentioned in the README.

**Comment by madziaf** [comment]
[Here](https://github.com/CodePadawans/ataru/blob/30-validate-codesamples/test/test_converter_test.rb#L12-L17) is an issue to discuss. If the code stays that way, the user will get from the test runner (minitest) the error message, that 'a' in not known.
Do we want the test runner to throw an error, or should there be a warning from ataru before?

**Comment by code-later** [comment]
As I understand this, it is an incomplete code example and thus should not throw the raw error but should give an ataru warning/error. The question is how do you determine if you should raise a custom, ataru-related error or just letting shit hit the fan (not handling the error at all)?

You eventually have two options: agree on some errors to be handled by ataru or to just rescue everything. When I think about it, it would be better to handle everything (at least everything that is kind of `StandardError`). Doing so will always give you the possibility to hint to the original code example rather than just giving some strange error with an arbitrary backtrace.

**Comment by schultyy** [comment]
Given the case that the complete code example is `a #=> 5` then it is ok when the test runner throws an error since it's the user's fault that they didn't put in a self contained code example.

**Comment by madziaf** [comment]
@railsbros-dirk we talked about your answer and understood it like that:
if there is a `StandardError` raised by `eval`, than it should be captured by ataru with `begin...rescue` and ataru should produce its own warning/error with a backtrace to the original code example

**Comment by code-later** [comment]
@madziaf yes, you understood that correctly. And therefore I disagree with @schultyy because just throwing an error will not help the user to find and fix the problem.

**Comment by nanoparsec** [comment]
Closed ans solved with Pull Request #38
